#regcmd "_hsp3cmdinit@4","hsplua.dll"
#cmd hl_newstate                0x00
#cmd hl_switchstate             0x01
#cmd hl_close                   0x02
#cmd hl_gccollect               0x04
#cmd hl_gcgen                   0x05
#cmd hl_gcinc                   0x06
#cmd hl_gcrestart               0x07
#cmd hl_gcsetpause              0x08
#cmd hl_gcsetstepmul            0x09
#cmd hl_gcstep                  0x0a
#cmd hl_gcstop                  0x0b
#cmd hl_pop                     0x10
#cmd hl_pushboolean             0x11
#cmd hl_pushfunction            0x12
#cmd hl_pushinteger             0x13
#cmd hl_pushlightuserdata       0x14
#cmd hl_pushlstring             0x15
#cmd hl_pushnil                 0x16
#cmd hl_pushnumber              0x17
#cmd hl_pushstring              0x18
#cmd hl_pushvalue               0x19
#cmd hl_pushvarptr              0x1a
#cmd hl_gettable                0x1b
#cmd hl_getmetatable            0x1c
#cmd hl_getglobal               0x1d
#cmd hl_getfield                0x1e
#cmd hl_settable                0x1f
#cmd hl_setmetatable            0x20
#cmd hl_setglobal               0x21
#cmd hl_setfield                0x22
#cmd hl_pushglobaltable         0x23
#cmd hl_newtable                0x24
#cmd hl_newmetatable            0x25
#cmd hl_error                   0x28
#cmd hl_pushdim                 0x29
#cmd hl_isboolean               0x80
#cmd hl_iscfunction             0x81
#cmd hl_isfunction              0x82
#cmd hl_islightuserdata         0x83
#cmd hl_isnil                   0x84
#cmd hl_isnone                  0x85
#cmd hl_isnoneornil             0x86
#cmd hl_isnumber                0x87
#cmd hl_isstring                0x88
#cmd hl_istable                 0x89
#cmd hl_isthread                0x8a
#cmd hl_isuserdata              0x8b
#cmd hl_toboolean               0x90
#cmd hl_tocfunction             0x91
#cmd hl_tointeger               0x92
#cmd hl_tonumber                0x93
#cmd hl_topointer               0x94
#cmd hl_tostring                0x95
#cmd hl_tolstring               0x96
#cmd hl_touserdata              0x97
#cmd hl_gccount                 0x98
#cmd hl_gcisrunning             0x99
#cmd hl_gettop                  0x9A
#cmd hl_pcall                   0x9B
#cmd hl_dofile                  0x9C
#cmd hl_dostring                0x9D
#cmd hl_seekvar                 0x9E
